
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.appName }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.appName }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.appName }}
  template:
    metadata:
      labels:
        app: {{ .Values.appName }}
    spec:
      imagePullSecrets:
        - name: {{ .Values.appName }}-secret
      containers:
        - name: {{ .Values.appName }}
          image: "{{ .Values.image.name }}:{{ .Values.image.tag }}"
          ports:
            - containerPort: 4000
          env:
            - name: TIMEZONE
              value: "Asia/Manila"
            - name: DEVICE_IP
              values: "192.168.254.200"
            - name: DEVICE_PORT
              values: "4370"

     #     {{- if (.Values.onPrem | default false) }}
     #     volumeMounts:
     #       - name:
     #         mountPath:   # ‚Üê Change this to YOUR public directory
     #         subPath:
     #         readOnly:
   #       {{- end }}
  #    {{- if (.Values.onPrem | default false) }}
  #    volumes:
  #      - name:
  #        secret:
  #          secretName:
  #          defaultMode:
 #     {{- end }}
